### ISSUE TITLE
mqtt 重新连接服务器时 内存增多的问题

### ISSUE THREAD

**Issue by Qianhao2579** [hichard/mymqtt#1]
mqtt 重新连接后 内存明显增多

msh />free
total memory: 113256
used memory : 31196
maximum allocated memory: 32536
msh />[E/at.skt.sim800] sim0 device socket(0) wait send result timeout.
[E/mqtt] [70910] send ping rc: -1
[D/mqtt.sample] inter mqtt_offline_callback! time_num:1
[D/at.dev.sim800] link_status: 1
[E/at.clnt] execute command (AT+CIPCLOSE=0) failed!
[D/mqtt] restart!
[D/mqtt.sample] inter mqtt_connect_callback!
[D/mqtt] ipv4 address port: 1883
[D/mqtt] HOST = '***********'
[I/mqtt] MQTT server connect success.
[I/mqtt] Subscribe #0 ******************* OK!
[D/mqtt.sample] inter mqtt_online_callback!
msh />free
total memory: 113256
used memory : 31612
maximum allocated memory: 32988

**Comment by hichard** [comment]
好的，测试下给你回复

**Comment by Qianhao2579** [comment]
麻烦大佬看看了

**Comment by saiyn** [comment]
大佬看了没？我这也是同样的必现的内存泄露
